<?php

declare(strict_types=1);

$propertyAllowlist = [
    'action',
    'assignment_id',
    'affiliate_code',
    'affiliate_id',
    'attribution_id',
    'batch_index',
    'cart_id',
    'cart_identifier',
    'cart_instance',
    'cart_total_minor',
    'channel',
    'checkout',
    'checkout_session_id',
    'client_build',
    'client_family',
    'client_name',
    'client_origin',
    'client_origin_source',
    'client_platform',
    'client_transport',
    'client_version',
    'commission_minor',
    'component',
    'conversion_id',
    'conversion_type',
    'cookie_value',
    'currency',
    'entrypoint',
    'entity_id',
    'entity_type',
    'event_label',
    'experiment_contexts',
    'experiment_id',
    'experiment_slug',
    'external_reference',
    'first_order',
    'gateway',
    'has_email',
    'interaction_type',
    'item_count',
    'item_id',
    'item_name',
    'items_count',
    'landing_url',
    'line_total_minor',
    'medium',
    'method',
    'module_type',
    'notification_id',
    'order_id',
    'order_number',
    'order_reference',
    'payment_gateway',
    'previous_screen_name',
    'query',
    'quantity',
    'referrer_url',
    'refund_reason',
    'request_method',
    'route_name',
    'screen_name',
    'shipping_method',
    'source_event_id',
    'status',
    'subject_instance',
    'subtotal_minor',
    'surface',
    'telemetry_channel',
    'title',
    'total_minor',
    'total_quantity',
    'transaction_id',
    'unique_item_count',
    'unit_price_minor',
    'updated_count',
    'value_minor',
    'variant_code',
    'variant_id',
    'voucher_code',
    'voucher_id',
    'voucher_name',
    'voucher_type',
    'voucher_value',
];

$tablePrefix = 'signal_';

return [
    'database' => [
        'table_prefix' => $tablePrefix,
        'json_column_type' => env('SIGNALS_JSON_COLUMN_TYPE', env('COMMERCE_JSON_COLUMN_TYPE', 'json')),
        'tables' => [
            'tracked_properties' => $tablePrefix.'tracked_properties',
            'identities' => $tablePrefix.'identities',
            'sessions' => $tablePrefix.'sessions',
            'events' => $tablePrefix.'events',
            'daily_metrics' => $tablePrefix.'daily_metrics',
            'goals' => $tablePrefix.'goals',
            'segments' => $tablePrefix.'segments',
            'saved_reports' => $tablePrefix.'saved_reports',
            'alert_rules' => $tablePrefix.'alert_rules',
            'alert_logs' => $tablePrefix.'alert_logs',
        ],
    ],

    'features' => [
        'owner' => [
            'enabled' => true,
            'include_global' => false,
            'auto_assign_on_create' => true,
        ],
        'ua_parsing' => [
            'enabled' => true,
            'store_raw' => true,
        ],
        'ip_tracking' => [
            'enabled' => true,
            'anonymize' => false,
        ],
        'auth_tracking' => [
            'enabled' => false,
        ],
        'geolocation' => [
            'enabled' => true,
            'reverse_geocode' => [
                'enabled' => false,
                'async' => true,
                'store_raw_payload' => false,
            ],
        ],
        'monetary' => [
            'enabled' => false,
        ],
        'privacy' => [
            'property_allowlist' => $propertyAllowlist,
        ],
        'alerts' => [
            'evaluate_on_ingest' => [
                'enabled' => false,
                'queue' => true,
            ],
            'allow_inline_destinations' => false,
            'default_channels' => ['database'],
            'destinations' => [
                'email' => [],
                'webhook' => [],
                'slack' => [],
            ],
        ],
    ],

    'integrations' => [
        'browser' => [
            'enabled' => false,
            'auto_register_middleware' => true,
            'middleware_group' => 'web',
            'auto_inject' => true,
            'interaction_tracking' => [
                'enabled' => true,
                'include_rules_without_selector' => false,
            ],
            'identifiers' => [
                'visitor_cookie_name' => 'sig_vid',
                'session_cookie_name' => 'sig_sid',
                'visitor_cookie_ttl_seconds' => 31_536_000,
                'session_cookie_ttl_seconds' => 1_800,
                'path' => '/',
                'domain' => null,
                'secure' => null,
                'http_only' => true,
                'same_site' => 'lax',
            ],
            'tracked_property' => [
                'auto_create' => true,
                'slug' => 'commerce-browser',
                'name' => 'Commerce Browser',
            ],
            'identify' => [
                'enabled' => true,
            ],
            'geolocation' => [
                'enabled' => true,
            ],
        ],
        'cart' => [
            'enabled' => true,
            'listen_for_item_added' => true,
            'listen_for_item_removed' => true,
            'listen_for_cleared' => true,
            'item_added_event_name' => 'cart.item.added',
            'item_removed_event_name' => 'cart.item.removed',
            'cleared_event_name' => 'cart.cleared',
            'event_category' => 'cart',
        ],
        'filament_cart' => [
            'enabled' => false,
            'listen_for_snapshot_synced' => true,
            'listen_for_checkout_started' => true,
            'listen_for_abandoned' => true,
            'listen_for_high_value_detected' => true,
            'snapshot_synced_event_name' => 'cart.snapshot.synced',
            'checkout_started_event_name' => 'cart.checkout.started',
            'abandoned_event_name' => 'cart.abandoned',
            'high_value_detected_event_name' => 'cart.high_value.detected',
            'event_category' => 'cart',
            'tracked_property' => [
                'auto_create' => true,
                'slug' => 'commerce-cart',
                'name' => 'Commerce Cart',
            ],
        ],
        'checkout' => [
            'enabled' => true,
            'listen_for_started' => true,
            'listen_for_completed' => true,
            'started_event_name' => 'checkout.started',
            'event_name' => 'checkout.completed',
            'event_category' => 'checkout',
        ],
        'orders' => [
            'enabled' => true,
            'listen_for_paid' => true,
            'event_name' => 'order.paid',
            'event_category' => 'conversion',
        ],
        'vouchers' => [
            'enabled' => true,
            'listen_for_applied' => true,
            'listen_for_removed' => true,
            'applied_event_name' => 'voucher.applied',
            'removed_event_name' => 'voucher.removed',
            'event_category' => 'promotion',
        ],
        'affiliates' => [
            'enabled' => true,
            'listen_for_attributed' => true,
            'listen_for_conversion_recorded' => true,
            'attributed_event_name' => 'affiliate.attributed',
            'attributed_event_category' => 'acquisition',
            'conversion_event_name' => 'affiliate.conversion.recorded',
            'conversion_event_category' => 'conversion',
        ],
        'affiliate_network' => [
            'enabled' => true,
            'listen_for_offer_created' => true,
            'listen_for_offer_updated' => true,
            'listen_for_application_submitted' => true,
            'listen_for_application_approved' => true,
            'listen_for_network_conversion_recorded' => true,
        ],
    ],
];
